### ISSUE TITLE
us_tx_dallas illegal xml chars

### ISSUE THREAD

**Issue by pnoll1** [pnoll1/osmand_map_creation#22]
filtering us_tx_dallasTraceback (most recent call last):
  File "/opt/ogr2osm/ogr2osm.py", line 792, in <module>
    main()
  File "/opt/ogr2osm/ogr2osm.py", line 783, in main
    output()
  File "/opt/ogr2osm/ogr2osm.py", line 517, in output
    tag = etree.Element('tag', {'k':key, 'v':value})
  File "src/lxml/etree.pyx", line 3007, in lxml.etree.Element
  File "src/lxml/apihelpers.pxi", line 131, in lxml.etree._makeElement
  File "src/lxml/apihelpers.pxi", line 119, in lxml.etree._makeElement
  File "src/lxml/apihelpers.pxi", line 299, in lxml.etree._initNodeAttributes
  File "src/lxml/apihelpers.pxi", line 310, in lxml.etree._addAttributeToNode
  File "src/lxml/apihelpers.pxi", line 1493, in lxml.etree._utf8
ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters

need to identify and determine if filters can/should be added to catch

**Comment by pnoll1** [comment]
Db has 826960 addresses, osm file has 825518, 1442 number=0 addresses are ignored when pulling data from db. No data seems to be lost so error had to occur at end of file since data stops being processed after this error. As a double check. I ran regular expression used to find illegal xml on the street, unit and postcode fields and found nothing.

**Comment by pnoll1** [comment]
No repeat of this issue and no way to reproduce.
