### ISSUE TITLE
PR Run Issue

### ISSUE THREAD

**Issue by pnoll1** [pnoll1/osmand_map_creation#36]
log: 
2022-01-25 00:24:03,968 writing osm file for us/pr/statewide-addresses-state.geojson
2022-01-25 00:24:08,055 us_pr_statewide_addresses_state is hashes only
2022-01-25 00:24:08,055 Expecting value: line 1 column 1 (char 0)
2022-01-25 00:24:29,071 osm update finished for us:pr
2022-01-25 00:24:30,318 us:pr Merge Finished

terminal error: 
Traceback (most recent call last):
  File "/home/pat/projects/osmand_map_creation/osmand_osm/osm/./processing.py", line 261, in prep_for_qa
    stats = run('osmium fileinfo -ej {0}'.format(working_area.master_list[-1].path_osm), shell=True, capture_output=True ,check=True , encoding='utf8')
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/pat/projects/osmand_map_creation/osmand_osm/osm/./processing.py", line 423, in run_all
    stats, stats_area, stats_final = prep_for_qa(working_area)
  File "/home/pat/projects/osmand_map_creation/osmand_osm/osm/./processing.py", line 263, in prep_for_qa
    logging.error(e.stderr)
AttributeError: 'IndexError' object has no attribute 'stderr'

pg2osm appears to run twice when there is only one source, correctly the first time then erroring out in pg2osm on the second which removes it from the master list then reaching an unrecoverable error in prep_for_qa where the list is required to be a nonempty list.  Error most likely at creating master list.

**Comment by pnoll1** [comment]
Need to improve error handling in prep_for_qa. An empty master list should mean no OA data has been added and should be logged. 

It would also be a good idea to check for this earlier instead of relying on the user to know there's no OA data for this area.

**Comment by pnoll1** [comment]
Osmium fileinfo after ogr2osm call returns error: OSM tag value is too long. Since there is no error handling on that statment, the error gets picked up by the next except block and sets off a weird chain of errors. 

This exception handling should be generalized since the file being hashes only is not the only possible issue.

**Comment by pnoll1** [comment]
error handling added in 2a6cf906d2f2efcc6fa183218a85b09fed96be45

data issue will be handled in #40
