### ISSUE TITLE
OsmAndMapCreator exit status 137

### ISSUE THREAD

**Issue by pnoll1** [pnoll1/osmand_map_creation#54]
Ca_on and Ca_qc both failed with:

Traceback (most recent call last):
  File "/home/pat/projects/osmand_map_creation/osmand_osm/osm/./processing.py", line 530, in <module>
    main()
  File "/home/pat/projects/osmand_map_creation/osmand_osm/osm/./processing.py", line 514, in main
    update_run_all_build(args, area_list)
  File "/home/pat/projects/osmand_map_creation/osmand_osm/osm/./processing.py", line 428, in update_run_all_build
    run('cd ../..;java -Djava.util.logging.config.file=logging.properties -Xms64M -Xmx{0} -cp "./OsmAndMapCreator.jar:lib/OsmAnd-core.jar:./lib/*.jar" net.osmand.util.IndexBatchCreator batch.xml'.format(Xmx), shell=True, capture_output=True, check=True,encoding='utf8')
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'cd ../..;java -Djava.util.logging.config.file=logging.properties -Xms64M -Xmx22G -cp "./OsmAndMapCreator.jar:lib/OsmAnd-core.jar:./lib/*.jar" net.osmand.util.IndexBatchCreator batch.xml' returned non-zero exit status 137.

**Comment by pnoll1** [comment]
ca_on was still in build folder when ca_qc was started. ca_on was source of failure on both runs.

ca_on gen log didn't show anything useful. Can't find docs or source code for exit status 137. ca_on is probably largest file ran at 757M. Split it and run again since that's usually the problem.

**Comment by pnoll1** [comment]
splitting ca_on fixed. Couldn't find docs on error code
